import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/global/Nabvar";
import TopNav from "@/global/TopNavbar";
import Footer from "@/global/Footer";
import { Roboto_Condensed } from "@next/font/google";
const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Siddhartha School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoCondensed.className}>
        <TopNav />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
